### ISSUE TITLE
TS Enum declarations loose values

### ISSUE THREAD

**Issue by CADBIMDeveloper** [Elringus/DotNetJS#113]
Hi @Elringus ,

There is a problem with exposing .Net enums to the TypeScript. For example, I have an enum in C# code like:
```cs
public enum Severity
{
    Warning = 1,

    Error = 2
}
```

Values are missed when it's translated into TS like:
```ts
export enum Severity {
	Warning,
	Error
}
```

Moreover, when I try to pass this like that:
```ts
dotnet.Something.someFunction({ severety: SomeNamespace.Severity.Error });
```
it fails with serialization exception, so I have to pass it like
```ts
dotnet.Something.someFunction({ severety: 2 });
```

I can try to prepare a PR to fix that, but want to discuss the details first

**Comment by Elringus** [comment]
Check this: https://github.com/Elringus/DotNetJS#json-serializer-options
