### ISSUE TITLE
Add a CI workflow to lint .editorconfig

### ISSUE THREAD

**Issue by Elringus** [Elringus/DotNetJS#29]
If anyone is aware of a github action that will lint the repo files to comply with [.editorconfig](https://github.com/Elringus/DotNetJS/blob/main/.editorconfig), please let us know here. 

We've tried https://github.com/megalinter/megalinter and https://github.com/github/super-linter configured to run only https://github.com/editorconfig-checker/editorconfig-checker, but they're both very slow.

**Comment by dahlia** [comment]
Apparently editorconfig-checker provides the official Docker images too: <https://hub.docker.com/r/mstruebing/editorconfig-checker>.  As GitHub Actions allows to run any existing Docker images in workflows, it might be worth a try.

**Comment by Elringus** [comment]
@dahlia Works like a charm, thank you!
