### ISSUE TITLE
Incorrect emitted TS declaration

### ISSUE THREAD

**Issue by Aragas** [Elringus/DotNetJS#5]
Hi! Thanks for the great library!

Since CodeGen was merged, I switched to the emitted declaration files instead of using manually created ones based on the source code, but the issue is, the nesting is wrong!

Right now the declarations are emitted like this:
```typescript
export declare const dotnet: {
    BannerlordModuleManager: { }; // The C# bindings
    BootStatus: typeof BootStatus;
    ...
};
```

But dotnet.js exposes the variable via `exports.BannerlordModuleManager` instead of `exports.dotnet.BannerlordModuleManager`
So the correct declaration would be this:
```typescript
export declare const BannerlordModuleManager: { }; // The C# bindings
export declare const dotnet: {
    BootStatus: typeof BootStatus;
    ...
};
```

PS:
Writing it here because Discussions aren't setup. Since we both are from Russia, I can't setup PayPal donations via Ko-Fi because Russia<-->Russia transactions are banned. Do you know any way to bypass the restriction?

**Comment by Elringus** [comment]
Hey, I've assumed that `module.exports` (node) and `root.dotnet` (browser) both correspond to `dotnet`, which is the default library export object. Here is how it's currently mapped in the UMD template:

```js
(function (root, factory) {
    if (typeof exports === 'object' && typeof exports.nodeName !== 'string')
        factory(module.exports, global);
    else factory(root.dotnet, root);
}(typeof self !== 'undefined' ? self : this, function (exports, global) {
    // I'm assuming that 'exports' here correspond to the exported 'dotnet' object, 
    // so 'exports.Test = {};' would equal to 'dotnet.Test' for the consumer.
}
```

I've tested the generated declarations in TS by importing the library as `import { dotnet } from "dotnet"` and WebStorm was able to map the types. Are there any issues with consuming it otherwise?

PS: I've enabled the discussions.

**Comment by Aragas** [comment]
As I understand, the mappings from the declarations are valid on their own, but when checking the real picture at runtime they aren't, I found out about that when I setup tests and they were reporting about missing `dotnet` variable.
 I copy the `dotnet.*` files into the source folder, that's why the path is relative.
![image](https://user-images.githubusercontent.com/5411011/144076401-326e6a2c-ba90-4a1d-9b53-9259ea3514b4.png)

**Comment by Aragas** [comment]
And as I understand, `exports.Test = {};` != `dotnet.Test` when importing via `import { dotnet } from "dotnet"`. It will be valid if the import will be done via `import dotnet from "dotnet"`

**Comment by Aragas** [comment]
You can test it yourself by checking the example in the README with TS
```typescript
import dotnet from "dotnet.js";

...
// Will be highlighted by the IDE about `HelloWorld` missing, because it assumes it resited at `dotnet.dotnet.HelloWorld`
const guestName = dotnet.HelloWorld.GetName();
```

**Comment by Elringus** [comment]
Will it work if the generated types will be declared like this:

```ts
export declare const BannerlordModuleManager: { }; 
export declare const dotnet: {
    BannerlordModuleManager: typeof BannerlordModuleManager;
    BootStatus: typeof BootStatus;
    ...
};
```
?

Also, I'd like to add tests to check validity of the generated type definitions, but not sure if it's possible to use the typescript compiler for this.

**Comment by Aragas** [comment]
I was using my own types via a custom scoped package, here's a working declaration example https://github.com/BUTR/Bannerlord.ModuleManager/blob/9ac3485547ade96396c4cc42805f50e54df23249/src/DotNetJS.TypeScript/lib/types/wrapper.d.ts


> Will it work if the generated types will be declared like this:
> 
> ```ts
> export declare const BannerlordModuleManager: { }; 
> export declare const dotnet: {
>     BannerlordModuleManager: typeof BannerlordModuleManager;
>     BootStatus: typeof BootStatus;
>     ...
> };
> ```
> 
> ?
> 
> Also, I'd like to add tests to check validity of the generated type definitions, but not sure if it's possible to use the typescript compiler for this.

You can skip entirely the dotnet declaration and just export all members contained within it

Yea, I guess you can check the validity, TS checks it at compile time, here's an example https://github.com/BUTR/Bannerlord.ModuleManager/runs/4369883583?check_suite_focus=true#step:9:20

**Comment by Elringus** [comment]
Thank you, I'll look into this.

**Comment by Elringus** [comment]
I think it generates proper types now (https://github.com/Elringus/DotNetJS/pull/6#issuecomment-983010785), but I'm still not sure how to implement the test: https://github.com/Elringus/DotNetJS/blob/47ca8796f39e26c1a9bc3b1a5b76e4226981bb56/JavaScript/dotnet-runtime/test/packed.js#L40

I've tried using `child_process.exec` to run tsc over the generated file, but wasn't able to make it work.

**Comment by Aragas** [comment]
I don't think it's viable to test the TS definitions from a JS environment
I guess the best would be to have a typescript environment and test setup, so both the compiler could do the check at compile-time and the TS tests at runtime.
The way I implemented it, I converted everything to TS, allowed JS and tested both JS and TS this way. Here are the [tests](https://github.com/BUTR/Bannerlord.ModuleManager/tree/master/src/Bannerlord.ModuleManager.TypeScript/src/test)

**Comment by Elringus** [comment]
Makes sense. Not sure if this one test justifies converting all the suite to TS, though. Maybe comparing the generated file with a reference is enough: https://github.com/Elringus/DotNetJS/blob/04dd07c4964541de7761075d769e983be1de21d9/JavaScript/dotnet-runtime/test/packed.js#L40

Anyway, latest nuget package should produce correct types now. Please let me know if it solves the issue.

**Comment by Aragas** [comment]
Sure, such test should be enough to cover TS generation!
And yea, the package emits everything correctly! Closing the issue, thanks!
