### ISSUE TITLE
Add // <auto-generated /> comment to source generator output 

### ISSUE THREAD

**Issue by Skleni** [Elringus/DotNetJS#68]
Can you add a `// <auto-generated />` comment at the top of the generated files?

According to [this issue](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3299), this is the way to go to avoid triggering StyleCop rules.

**Comment by Elringus** [comment]
Based on the issue you've linked, it looks like adding `g` suffix to the generated file names should also work. Is https://github.com/Elringus/DotNetJS/pull/69 ok?

**Comment by Skleni** [comment]
Sure, thanks for the fast reply. :)
