### ISSUE TITLE
Non Program methods not generated

### ISSUE THREAD

**Issue by promontis** [Elringus/DotNetJS#86]
I've noticed that methods are not generated for classes other than `Program`. So, if for example `Program` has a method that returns an object of type `Foo`, and `Foo` has a method `Bar()`, `Bar()` isn't generated for the typescript definition.

Is that by design or am I doing something wrong?

**Comment by Elringus** [comment]
Bindings are only generated for static methods annotated with the interop attributes. It's also possible to interop with instances, but that's entirely on the .NET side, this project has nothing extra for the case.

**Comment by promontis** [comment]
So, the surface area for any .net API should be fully expressed as ONLY static methods (annotated with the interop attribute) in the `Program` class?

**Comment by Elringus** [comment]
Class doesn't matter.
