### ISSUE TITLE
Why does typescript definitions render any?

### ISSUE THREAD

**Issue by promontis** [Elringus/DotNetJS#88]
I have the following C# code:

```csharp
[JSInvokable]
    public static EquationSystem.SolveResult Move(IEntity entity, Vector3 pos)
    {
        var editor = GetEditor();
        var moveTool = new MoveTool();
        return moveTool.Move(entity, editor.ActiveFeature, pos);
    }
```
Vector3 is a struct from System.Numerics.Vectors.dll.

This renders the following typescript:

```ts
export namespace Bindings {
    export function Move(entity: Bindings.IEntity, pos: any): Bindings.SolveResult;
}
```

Do you know why `pos` is of type `any`?

**Comment by Elringus** [comment]
All runtime assemblies (Microsoft.* and System.*) are ignored when resolving types. It's assumed that you will use only custom types when defining bindings, because most of the built-in types won't work with interop serialization anyway.

**Comment by promontis** [comment]
Ok that makes sense!
